### ISSUE TITLE
The theme is strange

### ISSUE THREAD

**Issue by chenzj-king** [fengdai/FragmentMaster#6]
I use the FragmentMaster.I find that my theme setting can't work properly.my editText/background... is black.wo set the background to the  xml parent point.but it can't work also.I must set the next point background.I think it's  so complicated.can you help me to solve this problem.Thanks

**Comment by fengdai** [comment]
Can you post your xml?

**Comment by chenzj-king** [comment]
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@mipmap/log_in_background"
    android:orientation="vertical">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginTop="20dp"
        android:gravity="center"
        android:orientation="horizontal">

        <ImageView
            android:id="@+id/register_or_password_back"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:padding="5dp"
            android:src="@mipmap/cube_mints_icon_top_back" />

        <TextView
            android:id="@+id/register_or_password_title"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_weight="1"
            android:gravity="center"
            android:text="注册"
            android:textColor="@color/white"
            android:textSize="25sp" />

    </LinearLayout>


    <LinearLayout
        android:id="@+id/register_or_password_layout1"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginBottom="10dp"
        android:layout_marginTop="10dp"
        android:orientation="horizontal">

        <TextView
            android:id="@+id/register_or_password_layout1_text1"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="账号：" />

        <EditText
            android:id="@+id/register_or_password_layout1_edittext1"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_weight="1" />

        <TextView
            android:id="@+id/register_or_password_getverification_again"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="" />
    </LinearLayout>


</LinearLayout>



the EditText run in nexus4 will black background.This xml use for Fragment.

**Comment by fengdai** [comment]
Can you post your theme's xml used for this Fragment?

**Comment by chenzj-king** [comment]
I use the ```@Configuration(theme = R.style.Theme_AppCompat_Light) ``` toset the fragement theme.It work.thanks.
