### ISSUE TITLE
How to used it in ViewPager ?

### ISSUE THREAD

**Issue by ggchxx** [fengdai/FragmentMaster#8]
For Exp: 
        List<Fragment> fragments = new ArrayList<>();
        fragments.add(Demo1Fragment.newInstance());
        fragments.add(Demo2Fragment.newInstance());
        FragmentAdapter adapter =
                new FragmentAdapter(getActivity().getSupportFragmentManager(), fragments, titles);
        mViewPager.setAdapter(adapter);
        mTabLayout.setupWithViewPager(mViewPager);

**Comment by fengdai** [comment]
Do as you have done above. FragmentMaster is not designed to simplify the code in this use case.

**Comment by ggchxx** [comment]
Oh,Thinks, I think the other way.
